Cu 862kjqyq6 pro dashboard update appointments
edgar-care/frontend pull request #80
Opened 2024-02-26 20:22 UTC by LeBaku

# Description

Add a button to modify the appointments

### Click Up reference

[CU-862kjqyq6](https://app.clickup.com/t/862kjqyq6)

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [X] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [X] I have assigned this PR to myself
- [X] I have added at least 1 reviewer
- [X] I have added the needed labels
- [X] I have linked this PR to a clickup task
- [X] I have tested this code
- [X] I have added / updated tests (unit / functionals / end-to-end / ...)
- [ ] I have updated the README and other relevant documents (guides...)
- [ ] I have added sufficient documentation both in code, as well as in the READMEs

2024-02-26 20:22 UTC, Lucas-COX commented
Task linked: [CU-862kjqyq6 pro-dashboard-update-appointments](https://app.clickup.com/t/862kjqyq6)

2024-02-26 20:22 UTC, Lucas-COX commented
Task linked: [CU-862kjqyq0 pro-dashboard-display-appointments](https://app.clickup.com/t/862kjqyq0)

2024-03-05 18:36 UTC, lucas-louis commented on edgar-doctor/src/components/app/dashboardPages/appointments/AppointmentSlotHour.tsx
You can add a `transition` to add a transition to the hover effect

2024-03-05 18:46 UTC, lucas-louis commented on edgar-doctor/src/components/app/dashboardPages/appointments/modals/UpdateAppointmentSubmitButton.tsx
> +		if (!selectedAppointmentId) toast({ title: 'Veuillez sélectionner un rendez-vous', status: 'error' });
Wrong variable, this one is always defined...

2024-03-05 18:47 UTC, lucas-louis commented on edgar-doctor/src/components/app/dashboardPages/appointments/modals/UpdateAppointmentContent.tsx
> +								(_, index) =>
Do not display slots that are before the actual day/ hour => you can't booked a slot in the past

2024-03-16 12:08 UTC, lucas-louis requested changes
There is still a conversation to fix...

2024-03-23 18:20 UTC, lucas-louis approved these changes
LGTM

2024-04-11 08:44 UTC, lucas-louis requested changes

2024-04-11 08:44 UTC, lucas-louis commented on edgar-doctor/src/components/app/dashboardPages/appointments/AppointmentsCards.tsx
> +						maxPageNumbers={countMaxNumberPage(appointments, 3)}
It's not `appointments` but `upcomingAppointments` because your pagination handle the display of upcomingAppointments and not overall appointments

2024-04-11 08:44 UTC, lucas-louis commented on edgar-doctor/src/components/app/dashboardPages/appointments/AppointmentsCards.tsx
> +						maxPageNumbers={countMaxNumberPage(appointments, 3)}
Same as the other one

2024-04-11 08:44 UTC, lucas-louis commented on edgar-app/src/utils/navigation/countMaxNumberPage.ts
It's not formated

2024-04-11 08:44 UTC, lucas-louis commented on edgar-app/src/utils/navigation/paginationHandler.ts
It's not formated

2024-04-11 14:51 UTC, lucas-louis approved these changes
LGTM

2024-04-11 14:53 UTC, merged