feat: app - Simulation Introduction
edgar-care/frontend pull request #82
Opened 2024-02-28 13:06 UTC by LeBaku

# Description

Create/Modify the first page of the introduction in the simulation part

### Click Up reference

[CU-86bxb9u3a](https://app.clickup.com/t/86bxb9u3a)

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [X] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [X] I have assigned this PR to myself
- [X] I have added at least 1 reviewer
- [X] I have added the needed labels
- [X] I have linked this PR to a clickup task
- [X] I have tested this code
- [X] I have added / updated tests (unit / functionals / end-to-end / ...)
- [ ] I have updated the README and other relevant documents (guides...)
- [ ] I have added sufficient documentation both in code, as well as in the READMEs

2024-02-28 13:06 UTC, Lucas-COX commented
Task linked: [CU-86bxb9u3a app-simulation-introduction](https://app.clickup.com/t/86bxb9u3a)

2024-03-05 14:46 UTC, lucas-louis requested changes
⚠️ Responsive needed + additional fixes

2024-03-05 14:46 UTC, lucas-louis commented on edgar-app/src/app/simulation/conditions/page.tsx
> +					</HStack>
- You need to transform it in a button to avoid selecting text
- Create a component for this button
- Add an hover animation like in the Figma

2024-03-05 14:46 UTC, lucas-louis commented on edgar-app/src/app/simulation/content.tsx
> +				Bienvenue dans votre simulation, je m’appel Edgar et je serai votre assistant tout au long de cette
"Je m'appelle"

2024-03-05 14:46 UTC, lucas-louis commented on edgar-app/src/app/simulation/content.tsx
> +			</Box>
Same as before

2024-03-05 14:46 UTC, lucas-louis commented on edgar-app/src/app/simulation/connection/page.tsx
> +				<Link href="/simulation/connection">
That's weird...

2024-03-05 14:46 UTC, lucas-louis commented on edgar-app/src/app/simulation/connection/page.tsx
> +							<Link href="app.edgar-sante.fr/login?redirect=/simulation/start">
Same

2024-03-05 14:46 UTC, lucas-louis commented on edgar-app/src/app/simulation/connection/page.tsx
> +						<Button variant="secondary">
Same

2024-03-05 14:46 UTC, lucas-louis commented on edgar-app/src/app/simulation/start/page.tsx
You need to handle the automatic redirection if the user is not authenticated.

2024-03-05 14:46 UTC, lucas-louis commented on edgar-app/src/app/simulation/start/page.tsx
> +				</Link>
Same (button)

2024-03-05 14:46 UTC, lucas-louis commented on edgar-app/src/components/simulationPages/SimulationLayout.tsx
> +	<VStack py="32px" px="64px" bgColor="blue.700" w="100%" borderRadius="48px" h="100%" justifyContent="space-between">
Just `justify` no need for `justifyContent`, same for `bgColor` only `bg` works

2024-03-25 13:57 UTC, lucas-louis requested changes

2024-03-25 13:57 UTC, lucas-louis commented on edgar-app/src/app/simulation/conditions/content.tsx
> +		router.push(redirection);
You can merge these two lines

2024-03-25 13:57 UTC, lucas-louis commented on edgar-app/src/app/simulation/conditions/content.tsx
> +					méthodes de soins. <br />
Remove the `<br />`

2024-03-25 13:57 UTC, lucas-louis commented on edgar-app/src/components/simulationPages/SimulationButton.tsx
> +				<Text size="boldXl" color={isHover ? 'blue.700' : 'white'}>
You can use the `_hover` properties instead of making a ternary

2024-03-25 13:57 UTC, lucas-louis commented on edgar-app/src/components/simulationPages/SimulationButton.tsx
> +					color={isHover ? 'blue.700' : 'white'}
You can use the `_hover` properties instead of making a ternary

2024-03-25 13:57 UTC, lucas-louis commented on edgar-app/src/components/simulationPages/SimulationLayout.tsx
> +			<VStack w="100%" h="108px"></VStack>
`<VStack w="100%" h="108px" />` is better

2024-03-25 13:57 UTC, lucas-louis commented on edgar-app/src/components/simulationPages/SimulationLayout.tsx
> +	const isMobile = useBreakpointValue({ base: true, md: false });
Missing line break

2024-04-08 18:58 UTC, merged