feat: app - Dashboard Home Treatment Follow Up
edgar-care/frontend pull request #87
Opened 2024-03-23 15:02 UTC by LeBaku

# Description

Create the treatment follw up card in the dashboard

### Click Up reference

[CU-86bxb9tvx](https://app.clickup.com/t/86bxb9tvx)

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [X] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [X] I have assigned this PR to myself
- [X] I have added at least 1 reviewer
- [X] I have added the needed labels
- [X] I have linked this PR to a clickup task
- [X] I have tested this code
- [X] I have added / updated tests (unit / functionals / end-to-end / ...)
- [ ] I have updated the README and other relevant documents (guides...)
- [ ] I have added sufficient documentation both in code, as well as in the READMEs

2024-03-23 15:02 UTC, Lucas-COX commented
Task linked: [CU-86bxb9tvx app-dashboard-home-treatmentFollowUp](https://app.clickup.com/t/86bxb9tvx)

2024-03-24 12:54 UTC, lucas-louis requested changes
You need to connect the backend

2024-03-24 12:54 UTC, lucas-louis commented on edgar-app/src/components/dashboardPages/home/HomeTreatmentsCard.tsx
> +				<Link href="/dashboard/chat">
Bad url

2024-03-24 12:54 UTC, lucas-louis commented on edgar-app/src/components/dashboardPages/home/HomeTreatmentsCard.tsx
> +					</VStack>
You need to handle the data in another way, the backend will send you a list of treatments checked and you need to get the medical info of the patient and for each treatment you need to group and to display the treatment in the good order

2024-03-24 12:54 UTC, lucas-louis commented on edgar-app/src/components/dashboardPages/home/HomeTreatmentsCard.tsx
> +							traitements
You don't need to use `<br />`

2024-05-08 09:39 UTC, lucas-louis approved these changes
LGTM

2024-05-08 14:37 UTC, merged